// See https://svelte.dev/docs/kit/types#app.d.ts
// for information about these interfaces

declare global {
  namespace App {
    // interface Error {}
    interface Locals {
      isAuthenticated: boolean;
    }
    // interface PageData {}
    // interface PageState {}
    interface Platform {
      env: Env; // Generated by 'wrangler types'
      context: ExecutionContext;
      caches: CacheStorage & { default: Cache };
    }
  }
}

export {};
